# Generated by Django 5.0.4 on 2024-04-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('skp_tahunan', models.CharField(max_length=100)),
                ('jurnal_harian', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('satuan', models.CharField(max_length=50)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('lampiran', models.FileField(upload_to='lampiran/')),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=5)),
                ('komentar', models.TextField(blank=True, null=True)),
                ('tanggal_isi', models.DateField()),
            ],
            options={
                'db_table': 'jurnal_harian',
            },
        ),
    ]
